export const paginationData = [
    {
      id: 1,
      artistName: "White Sand",
      username: "Victoria Wilson",
      fullName: "James Arthur",
      role: "Super Admin",
      skill: "Songwriting",
      date: "20/2/2023",
      amount: "$1779.53",
      email: "victoriawilson@gmail.com",
      location: "Lagos, NG",
      startDate: "20/2/2023",
      endDate: "20/2/2023",
      collaborator: "5 Collaborators",
      title: "Victoria Wilson 20/2/2023",
      rating: "4.1",
      approved: false,
      description: "The project is about  making music and collab with the people and every",
      requestTitle: "INSPIRING & POSITIVE BLUES/BLUESY SONGS w...",
      files: "4 Files",
      viewFiles: "View Files",
      received: "Received",
      payment: "Payment",
      withdrawal: "Withdrawal",
      owner: "Razu Music Inc.",
      recentActivity: "30 Minutes ago",
      transactionDesc: "Payment made to Razu Music Inc. for subscription fee for the month of June 2023.",
      status: "active",
      bcolor:  "#DFFAD5",
      color: "#2AA836",
    },
    {
      id: 2,
      artistName: "Yellow Sand",
      username: "Victoria Wilson",
      fullName: "Robert Lee",
      role: "Admin",
      skill: "Producer",
      date: "10/3/2023",
      amount: "$1779.53",
      email: "victoriawilson@gmail.com",
      location: "Lagos, NG",
      startDate: "20/2/2023",
      endDate: "20/2/2023",
      collaborator: "5 Collaborators",
      title: "Victoria Wilson 20/2/2023",
      rating: "4.1",
      approved: false,
      description: "The project is about  making music and collab with the people and every",
      requestTitle: "INSPIRING & POSITIVE BLUES/BLUESY SONGS w...",
      files: "4 Files",
      viewFiles: "View Files",
      received: "Received",
      payment: "Payment",
      withdrawal: "Withdrawal",
      owner: "Razu Music Inc.",
      recentActivity: "30 Minutes ago",
      transactionDesc: "Payment made to Razu Music Inc. for subscription fee for the month of June 2023.",
      status: "Deactivated",
      bcolor:  "#F9DBCF",
      color: "#931722",
    },
    {
      id: 3,
      artistName: "Blue Sand",
      username: "Victoria Wilson",
      fullName: "Janice Smith",
      role: "Admin",
      skill: "Mixer",
      date: "17/4/2023",
      amount: "$1779.53",
      email: "victoriawilson@gmail.com",
      location: "Lagos, NG",
      startDate: "20/2/2023",
      endDate: "20/2/2023",
      collaborator: "5 Collaborators",
      title: "Victoria Wilson 20/2/2023",
      rating: "4.1",
      approved: false,
      description: "The project is about  making music and collab with the people and every",
      requestTitle: "INSPIRING & POSITIVE BLUES/BLUESY SONGS w...",
      files: "4 Files",
      viewFiles: "View Files",
      received: "Received",
      payment: "Payment",
      withdrawal: "Withdrawal",
      owner: "Razu Music Inc.",
      recentActivity: "30 Minutes ago",
      transactionDesc: "Payment made to Razu Music Inc. for subscription fee for the month of June 2023.",
      status: "Deactivated",
      bcolor:  "#F9DBCF",
      color: "#931722",
    },
    {
      id: 4,
      artistName: "Purple Sand",
      username: "Victoria Wilson",
      fullName: "Reese Benard",
      role: "Admin",
      skill: "Songwriting",
      date: "30/6/2023",
      amount: "$1779.53",
      email: "victoriawilson@gmail.com",
      location: "Lagos, NG",
      startDate: "20/2/2023",
      endDate: "20/2/2023",
      collaborator: "5 Collaborators",
      title: "Victoria Wilson 20/2/2023",
      rating: "4.1",
      approved: false,
      description: "The project is about  making music and collab with the people and every",
      requestTitle: "INSPIRING & POSITIVE BLUES/BLUESY SONGS w...",
      files: "4 Files",
      viewFiles: "View Files",
      received: "Received",
      payment: "Payment",
      withdrawal: "Withdrawal",
      owner: "Razu Music Inc.",
      recentActivity: "30 Minutes ago",
      transactionDesc: "Payment made to Razu Music Inc. for subscription fee for the month of June 2023.",
      status: "Deactivated",
      bcolor:  "#F9DBCF",
      color: "#931722",
    },
    {
      id: 5,
      artistName: "Orange Sand",
      username: "Victoria Wilson",
      fullName: "Bryce Young",
      role: "Admin",
      skill: "Songwriting",
      date: "08/05/2023",
      amount: "$1779.53",
      email: "victoriawilson@gmail.com",
      location: "Lagos, NG",
      startDate: "20/2/2023",
      endDate: "20/2/2023",
      collaborator: "5 Collaborators",
      title: "Victoria Wilson 20/2/2023",
      rating: "4.1",
      approved: false,
      description: "The project is about  making music and collab with the people and every",
      requestTitle: "INSPIRING & POSITIVE BLUES/BLUESY SONGS w...",
      files: "4 Files",
      viewFiles: "View Files",
      received: "Received",
      payment: "Payment",
      withdrawal: "Withdrawal",
      owner: "Razu Music Inc.",
      recentActivity: "30 Minutes ago",
      transactionDesc: "Payment made to Razu Music Inc. for subscription fee for the month of June 2023.",
      status: "Deactivated",
      bcolor:  "#F9DBCF",
      color: "#931722",
    },
     {
      id: 6,
      artistName: "Black Sand",
      username: "Victoria Wilson",
      fullName: "James Arthur",
      role: "Viewer",
      skill: "Songwriting",
      date: "20/2/2023",
      amount: "$1779.53",
      email: "victoriawilson@gmail.com",
      location: "Lagos, NG",
      startDate: "20/2/2023",
      endDate: "20/2/2023",
      collaborator: "5 Collaborators",
      title: "Victoria Wilson 20/2/2023",
      rating: "4.1",
      approved: false,
      description: "The project is about  making music and collab with the people and every",
      requestTitle: "INSPIRING & POSITIVE BLUES/BLUESY SONGS w...",
      files: "4 Files",
      viewFiles: "View Files",
      received: "Received",
      payment: "Payment",
      withdrawal: "Withdrawal",
      owner: "Razu Music Inc.",
      recentActivity: "30 Minutes ago",
      transactionDesc: "Payment made to Razu Music Inc. for subscription fee for the month of June 2023.",
      status: "Paid",
      bcolor:  "#DFFAD5",
      color: "#2AA836",
    },
     {
      id: 7,
      artistName: "Grey Sand",
      username: "Victoria Wilson",
      fullName: "James Arthur",
      role: "Viewer",
      skill: "Songwriting",
      date: "20/2/2023",
      amount: "$1779.53",
      email: "victoriawilson@gmail.com",
      location: "Lagos, NG",
      startDate: "20/2/2023",
      endDate: "20/2/2023",
      collaborator: "5 Collaborators",
      title: "Victoria Wilson 20/2/2023",
      rating: "4.1",
      approved: false,
      description: "The project is about  making music and collab with the people and every",
      requestTitle: "INSPIRING & POSITIVE BLUES/BLUESY SONGS w...",
      files: "4 Files",
      viewFiles: "View Files",
      received: "Received",
      payment: "Payment",
      withdrawal: "Withdrawal",
      owner: "Razu Music Inc.",
      recentActivity: "30 Minutes ago",
      transactionDesc: "Payment made to Razu Music Inc. for subscription fee for the month of June 2023.",
      status: "Paid",
      bcolor:  "#DFFAD5",
      color: "#2AA836",
    },
     {
      id: 8,
      artistName: "White Sand",
      username: "Victoria Wilson",
      fullName: "James Arthur",
      role: "Viewer",
      skill: "Songwriting",
      date: "20/2/2023",
      amount: "$1779.53",
      email: "victoriawilson@gmail.com",
      location: "Lagos, NG",
      startDate: "20/2/2023",
      endDate: "20/2/2023",
      collaborator: "5 Collaborators",
      title: "Victoria Wilson 20/2/2023",
      rating: "4.1",
      approved: false,
      description: "The project is about  making music and collab with the people and every",
      requestTitle: "INSPIRING & POSITIVE BLUES/BLUESY SONGS w...",
      files: "4 Files",
      viewFiles: "View Files",
      received: "Received",
      payment: "Payment",
      withdrawal: "Withdrawal",
      owner: "Razu Music Inc.",
      recentActivity: "30 Minutes ago",
      transactionDesc: "Payment made to Razu Music Inc. for subscription fee for the month of June 2023.",
      status: "Paid",
      bcolor:  "#DFFAD5",
      color: "#2AA836",
    },
     {
      id: 9,
      artistName: "Greene Sand",
      username: "Victoria Wilson",
      fullName: "James Arthur",
      role: "Viewer",
      skill: "Songwriting",
      date: "20/2/2023",
      amount: "$1779.53",
      email: "victoriawilson@gmail.com",
      location: "Lagos, NG",
      startDate: "20/2/2023",
      endDate: "20/2/2023",
      collaborator: "5 Collaborators",
      title: "Victoria Wilson 20/2/2023",
      rating: "4.1",
      approved: false,
      description: "The project is about  making music and collab with the people and every",
      requestTitle: "INSPIRING & POSITIVE BLUES/BLUESY SONGS w...",
      files: "4 Files",
      viewFiles: "View Files",
      received: "Received",
      payment: "Payment",
      withdrawal: "Withdrawal",
      owner: "Razu Music Inc.",
      recentActivity: "30 Minutes ago",
      transactionDesc: "Payment made to Razu Music Inc. for subscription fee for the month of June 2023.",
      status: "Paid",
      bcolor:  "#DFFAD5",
      color: "#2AA836",
    },
     {
      id: 10,
      artistName: "Red Sand",
      username: "Victoria Wilson",
      fullName: "James Arthur",
      role: "Viewer",
      skill: "Songwriting",
      date: "20/2/2023",
      amount: "$1779.53",
      email: "victoriawilson@gmail.com",
      location: "Lagos, NG",
      startDate: "20/2/2023",
      endDate: "20/2/2023",
      collaborator: "5 Collaborators",
      title: "Victoria Wilson 20/2/2023",
      rating: "4.1",
      approved: false,
      description: "The project is about  making music and collab with the people and every",
      requestTitle: "INSPIRING & POSITIVE BLUES/BLUESY SONGS w...",
      files: "4 Files",
      viewFiles: "View Files",
      received: "Received",
      payment: "Payment",
      withdrawal: "Withdrawal",
      owner: "Razu Music Inc.",
      recentActivity: "30 Minutes ago",
      transactionDesc: "Payment made to Razu Music Inc. for subscription fee for the month of June 2023.",
      status: "Paid",
      bcolor:  "#DFFAD5",
      color: "#2AA836",
    },
    {
      id: 11,
      artistName: "Brown Sand",
      username: "Victoria Wilson",
      fullName: "James Arthur",
      role: "Viewer",
      skill: "Songwriting",
      date: "20/2/2023",
      amount: "$1779.53",
      email: "victoriawilson@gmail.com",
      location: "Lagos, NG",
      startDate: "20/2/2023",
      endDate: "20/2/2023",
      collaborator: "5 Collaborators",
      title: "Victoria Wilson 20/2/2023",
      rating: "4.1",
      approved: false,
      description: "The project is about  making music and collab with the people and every",
      requestTitle: "INSPIRING & POSITIVE BLUES/BLUESY SONGS w...",
      files: "4 Files",
      viewFiles: "View Files",
      received: "Received",
      payment: "Payment",
      withdrawal: "Withdrawal",
      owner: "Razu Music Inc.",
      recentActivity: "30 Minutes ago",
      transactionDesc: "Payment made to Razu Music Inc. for subscription fee for the month of June 2023.",
      status: "Paid",
      bcolor:  "#DFFAD5",
      color: "#2AA836",
      },
      {
      id: 12,
      artistName: "White Sand",
      username: "Victoria Wilson",
      fullName: "James Arthur",
      role: "Viewer",
      skill: "Songwriting",
      date: "20/2/2023",
      amount: "$1779.53",
      email: "victoriawilson@gmail.com",
      location: "Lagos, NG",
      startDate: "20/2/2023",
      endDate: "20/2/2023",
      collaborator: "5 Collaborators",
      title: "Victoria Wilson 20/2/2023",
      rating: "4.1",
      approved: false,
      description: "The project is about  making music and collab with the people and every",
      requestTitle: "INSPIRING & POSITIVE BLUES/BLUESY SONGS w...",
      files: "4 Files",
      viewFiles: "View Files",
      received: "Received",
      payment: "Payment",
      withdrawal: "Withdrawal",
      owner: "Razu Music Inc.",
      recentActivity: "30 Minutes ago",
      transactionDesc: "Payment made to Razu Music Inc. for subscription fee for the month of June 2023.",
      status: "Paid",
      bcolor:  "#DFFAD5",
      color: "#2AA836",
      },
      {
      id: 13,
      artistName: "White Sand",
      username: "Victoria Wilson",
      fullName: "James Arthur",
      role: "Viewer",
      skill: "Songwriting",
      date: "20/2/2023",
      amount: "$1779.53",
      email: "victoriawilson@gmail.com",
      location: "Lagos, NG",
      startDate: "20/2/2023",
      endDate: "20/2/2023",
      collaborator: "5 Collaborators",
      title: "Victoria Wilson 20/2/2023",
      rating: "4.1",
      approved: false,
      description: "The project is about  making music and collab with the people and every",
      requestTitle: "INSPIRING & POSITIVE BLUES/BLUESY SONGS w...",
      files: "4 Files",
      viewFiles: "View Files",
      received: "Received",
      payment: "Payment",
      withdrawal: "Withdrawal",
      owner: "Razu Music Inc.",
      recentActivity: "30 Minutes ago",
      transactionDesc: "Payment made to Razu Music Inc. for subscription fee for the month of June 2023.",
      status: "Paid",
      bcolor:  "#DFFAD5",
      color: "#2AA836",
      },
      {
      id: 14,
      artistName: "White Sand",
      username: "Victoria Wilson",
      fullName: "James Arthur",
      role: "Viewer",
      skill: "Songwriting",
      date: "20/2/2023",
      amount: "$1779.53",
      email: "victoriawilson@gmail.com",
      location: "Lagos, NG",
      startDate: "20/2/2023",
      endDate: "20/2/2023",
      collaborator: "5 Collaborators",
      title: "Victoria Wilson 20/2/2023",
      rating: "4.1",
      approved: false,
      description: "The project is about  making music and collab with the people and every",
      requestTitle: "INSPIRING & POSITIVE BLUES/BLUESY SONGS w...",
      files: "4 Files",
      viewFiles: "View Files",
      received: "Received",
      payment: "Payment",
      withdrawal: "Withdrawal",
      owner: "Razu Music Inc.",
      recentActivity: "30 Minutes ago",
      transactionDesc: "Payment made to Razu Music Inc. for subscription fee for the month of June 2023.",
      status: "Paid",
      bcolor:  "#DFFAD5",
      color: "#2AA836",
      },
      {
      id: 15,
      artistName: "White Sand",
      username: "Victoria Wilson",
      fullName: "James Arthur",
      role: "Viewer",
      skill: "Songwriting",
      skill: "Songwriting",
      date: "20/2/2023",
      amount: "$1779.53",
      email: "victoriawilson@gmail.com",
      location: "Lagos, NG",
      startDate: "20/2/2023",
      endDate: "20/2/2023",
      collaborator: "5 Collaborators",
      title: "Victoria Wilson 20/2/2023",
      rating: "4.1",
      approved: false,
      description: "The project is about  making music and collab with the people and every",
      requestTitle: "INSPIRING & POSITIVE BLUES/BLUESY SONGS w...",
      files: "4 Files",
      viewFiles: "View Files",
      received: "Received",
      payment: "Payment",
      withdrawal: "Withdrawal",
      owner: "Razu Music Inc.",
      recentActivity: "30 Minutes ago",
      transactionDesc: "Payment made to Razu Music Inc. for subscription fee for the month of June 2023.",
      status: "Paid",
      bcolor:  "#DFFAD5",
      color: "#2AA836",
      },
  ];
  